/**
 * 指标源配置表（自其它项目拷贝，为目录唯一数据源）。
 * 交易页指标面板由 build-indicators.ts 读取本文件并生成 TRADE_INDICATORS。
 *
 * - tech：技术指标，id/name 为展示名，由 tv-study.ts 映射到 TV createStudy 名
 * - 其它分类：带 code 的业务指标，Phase 2 接 API
 */
export enum CategoryEnum {
  tech = 'tech',
  market = 'market',
  liquidity = 'liquidity',
  sentiment = 'sentiment',
  options = 'options',
  chain = 'chain',
}

export interface SourceIndicatorItem {
  id: string;
  name: string;
  description: string;
  category: CategoryEnum;
  categoryName: string;
  code?: string;
}

export enum CategoryTextEnum {
  tech = '技术指标',
  market = '市场微观结构',
  liquidity = '流动性',
  sentiment = '情绪',
  options = '期权',
  chain = '链上',
}

export const indicatorList: SourceIndicatorItem[] = [

// 技术指标
  {
    id: '52 Week High/Low',
    name: '52 Week High/Low',
    description: '52 Week High/Low',
    category: CategoryEnum.tech,
    categoryName: CategoryTextEnum.tech,
  },
  {
    id: 'Accelerator Oscillator',
    name: 'Accelerator Oscillator',
    description: 'Accelerator Oscillator',
    category: CategoryEnum.tech,
    categoryName: CategoryTextEnum.tech,
  },
  {
    id: 'Accumulation/Distribution',
    name: 'Accumulation/Distribution',
    description: 'Accumulation/Distribution',
    category: CategoryEnum.tech,
    categoryName: CategoryTextEnum.tech,
  },
  {
    id: 'Accumulative Swing Index',
    name: 'Accumulative Swing Index',
    description: 'Accumulative Swing Index',
    category: CategoryEnum.tech,
    categoryName: CategoryTextEnum.tech,
  },
  {
    id: 'Advance/Decline',
    name: 'Advance/Decline',
    description: 'Advance/Decline',
    category: CategoryEnum.tech,
    categoryName: CategoryTextEnum.tech,
  },
  {
    id: 'Arnaud Legoux Moving Average',
    name: 'Arnaud Legoux Moving Average',
    description: 'Arnaud Legoux Moving Average',
    category: CategoryEnum.tech,
    categoryName: CategoryTextEnum.tech,
  },
  {
    id: 'Aroon',
    name: 'Aroon',
    description: 'Aroon',
    category: CategoryEnum.tech,
    categoryName: CategoryTextEnum.tech,
  },
  {
    id: 'Average Directional Index',
    name: 'Average Directional Index',
    description: 'Average Directional Index',
    category: CategoryEnum.tech,
    categoryName: CategoryTextEnum.tech,
  },
  {
    id: 'Average Price',
    name: 'Average Price',
    description: 'Average Price',
    category: CategoryEnum.tech,
    categoryName: CategoryTextEnum.tech,
  },
  {
    id: 'Average True Range',
    name: 'Average True Range',
    description: 'Average True Range',
    category: CategoryEnum.tech,
    categoryName: CategoryTextEnum.tech,
  },
  {
    id: 'Awesome Oscillator',
    name: 'Awesome Oscillator',
    description: 'Awesome Oscillator',
    category: CategoryEnum.tech,
    categoryName: CategoryTextEnum.tech,
  },
  {
    id: 'Balance of Power',
    name: 'Balance of Power',
    description: 'Balance of Power',
    category: CategoryEnum.tech,
    categoryName: CategoryTextEnum.tech,
  },
  {
    id: 'Bollinger Bands',
    name: 'Bollinger Bands',
    description: 'Bollinger Bands',
    category: CategoryEnum.tech,
    categoryName: CategoryTextEnum.tech,
  },
  {
    id: 'Bollinger Bands %B',
    name: 'Bollinger Bands %B',
    description: 'Bollinger Bands %B',
    category: CategoryEnum.tech,
    categoryName: CategoryTextEnum.tech,
  },
  {
    id: 'Bollinger Bands Width',
    name: 'Bollinger Bands Width',
    description: 'Bollinger Bands Width',
    category: CategoryEnum.tech,
    categoryName: CategoryTextEnum.tech,
  },
  {
    id: 'Chaikin Money Flow',
    name: 'Chaikin Money Flow',
    description: 'Chaikin Money Flow',
    category: CategoryEnum.tech,
    categoryName: CategoryTextEnum.tech,
  },
  {
    id: 'Chaikin Oscillator',
    name: 'Chaikin Oscillator',
    description: 'Chaikin Oscillator',
    category: CategoryEnum.tech,
    categoryName: CategoryTextEnum.tech,
  },
  {
    id: 'Chaikin Volatility',
    name: 'Chaikin Volatility',
    description: 'Chaikin Volatility',
    category: CategoryEnum.tech,
    categoryName: CategoryTextEnum.tech,
  },
  {
    id: 'Chande Kroll Stop',
    name: 'Chande Kroll Stop',
    description: 'Chande Kroll Stop',
    category: CategoryEnum.tech,
    categoryName: CategoryTextEnum.tech,
  },
  {
    id: 'Chande Momentum Oscillator',
    name: 'Chande Momentum Oscillator',
    description: 'Chande Momentum Oscillator',
    category: CategoryEnum.tech,
    categoryName: CategoryTextEnum.tech,
  },
  {
    id: 'Chop Zone',
    name: 'Chop Zone',
    description: 'Chop Zone',
    category: CategoryEnum.tech,
    categoryName: CategoryTextEnum.tech,
  },
  {
    id: 'Choppiness Index',
    name: 'Choppiness Index',
    description: 'Choppiness Index',
    category: CategoryEnum.tech,
    categoryName: CategoryTextEnum.tech,
  },
  {
    id: 'Commodity Channel Index',
    name: 'Commodity Channel Index',
    description: 'Commodity Channel Index',
    category: CategoryEnum.tech,
    categoryName: CategoryTextEnum.tech,
  },
  {
    id: 'Connors RSI',
    name: 'Connors RSI',
    description: 'Connors RSI',
    category: CategoryEnum.tech,
    categoryName: CategoryTextEnum.tech,
  },
  {
    id: 'Coppock Curve',
    name: 'Coppock Curve',
    description: 'Coppock Curve',
    category: CategoryEnum.tech,
    categoryName: CategoryTextEnum.tech,
  },
  {
    id: 'Correlation - Log',
    name: 'Correlation - Log',
    description: 'Correlation - Log',
    category: CategoryEnum.tech,
    categoryName: CategoryTextEnum.tech,
  },
  {
    id: 'Correlation Coefficient',
    name: 'Correlation Coefficient',
    description: 'Correlation Coefficient',
    category: CategoryEnum.tech,
    categoryName: CategoryTextEnum.tech,
  },
  {
    id: 'Detrended Price Oscillator',
    name: 'Detrended Price Oscillator',
    description: 'Detrended Price Oscillator',
    category: CategoryEnum.tech,
    categoryName: CategoryTextEnum.tech,
  },
  {
    id: 'Directional Movement',
    name: 'Directional Movement',
    description: 'Directional Movement',
    category: CategoryEnum.tech,
    categoryName: CategoryTextEnum.tech,
  },
  {
    id: 'Donchian Channels',
    name: 'Donchian Channels',
    description: 'Donchian Channels',
    category: CategoryEnum.tech,
    categoryName: CategoryTextEnum.tech,
  },
  {
    id: 'Double EMA',
    name: 'Double EMA',
    description: 'Double EMA',
    category: CategoryEnum.tech,
    categoryName: CategoryTextEnum.tech,
  },
  {
    id: 'Ease Of Movement',
    name: 'Ease Of Movement',
    description: 'Ease Of Movement',
    category: CategoryEnum.tech,
    categoryName: CategoryTextEnum.tech,
  },
  {
    id: "Elder's Force Index",
    name: "Elder's Force Index",
    description: "Elder's Force Index",
    category: CategoryEnum.tech,
    categoryName: CategoryTextEnum.tech,
  },
  {
    id: 'EMA Cross',
    name: 'EMA Cross',
    description: 'EMA Cross',
    category: CategoryEnum.tech,
    categoryName: CategoryTextEnum.tech,
  },
  {
    id: 'Envelopes',
    name: 'Envelopes',
    description: 'Envelopes',
    category: CategoryEnum.tech,
    categoryName: CategoryTextEnum.tech,
  },
  {
    id: 'Fisher Transform',
    name: 'Fisher Transform',
    description: 'Fisher Transform',
    category: CategoryEnum.tech,
    categoryName: CategoryTextEnum.tech,
  },
  {
    id: 'Guppy Multiple Moving Average',
    name: 'Guppy Multiple Moving Average',
    description: 'Guppy Multiple Moving Average',
    category: CategoryEnum.tech,
    categoryName: CategoryTextEnum.tech,
  },
  {
    id: 'Historical Volatility',
    name: 'Historical Volatility',
    description: 'Historical Volatility',
    category: CategoryEnum.tech,
    categoryName: CategoryTextEnum.tech,
  },
  {
    id: 'Hull Moving Average',
    name: 'Hull Moving Average',
    description: 'Hull Moving Average',
    category: CategoryEnum.tech,
    categoryName: CategoryTextEnum.tech,
  },
  {
    id: 'Ichimoku Cloud',
    name: 'Ichimoku Cloud',
    description: 'Ichimoku Cloud',
    category: CategoryEnum.tech,
    categoryName: CategoryTextEnum.tech,
  },
  {
    id: 'Keltner Channels',
    name: 'Keltner Channels',
    description: 'Keltner Channels',
    category: CategoryEnum.tech,
    categoryName: CategoryTextEnum.tech,
  },
  {
    id: 'Klinger Oscillator',
    name: 'Klinger Oscillator',
    description: 'Klinger Oscillator',
    category: CategoryEnum.tech,
    categoryName: CategoryTextEnum.tech,
  },
  {
    id: 'Know Sure Thing',
    name: 'Know Sure Thing',
    description: 'Know Sure Thing',
    category: CategoryEnum.tech,
    categoryName: CategoryTextEnum.tech,
  },
  {
    id: 'Least Squares Moving Average',
    name: 'Least Squares Moving Average',
    description: 'Least Squares Moving Average',
    category: CategoryEnum.tech,
    categoryName: CategoryTextEnum.tech,
  },
  {
    id: 'Linear Regression Curve',
    name: 'Linear Regression Curve',
    description: 'Linear Regression Curve',
    category: CategoryEnum.tech,
    categoryName: CategoryTextEnum.tech,
  },
  {
    id: 'Linear Regression Slope',
    name: 'Linear Regression Slope',
    description: 'Linear Regression Slope',
    category: CategoryEnum.tech,
    categoryName: CategoryTextEnum.tech,
  },
  {
    id: 'MA Cross',
    name: 'MA Cross',
    description: 'MA Cross',
    category: CategoryEnum.tech,
    categoryName: CategoryTextEnum.tech,
  },
  {
    id: 'MA with EMA Cross',
    name: 'MA with EMA Cross',
    description: 'MA with EMA Cross',
    category: CategoryEnum.tech,
    categoryName: CategoryTextEnum.tech,
  },
  {
    id: 'MACD',
    name: 'MACD',
    description: 'MACD',
    category: CategoryEnum.tech,
    categoryName: CategoryTextEnum.tech,
  },
  {
    id: 'Majority Rule',
    name: 'Majority Rule',
    description: 'Majority Rule',
    category: CategoryEnum.tech,
    categoryName: CategoryTextEnum.tech,
  },
  {
    id: 'Mass Index',
    name: 'Mass Index',
    description: 'Mass Index',
    category: CategoryEnum.tech,
    categoryName: CategoryTextEnum.tech,
  },
  {
    id: 'McGinley Dynamic',
    name: 'McGinley Dynamic',
    description: 'McGinley Dynamic',
    category: CategoryEnum.tech,
    categoryName: CategoryTextEnum.tech,
  },
  {
    id: 'Median Price',
    name: 'Median Price',
    description: 'Median Price',
    category: CategoryEnum.tech,
    categoryName: CategoryTextEnum.tech,
  },
  {
    id: 'Momentum',
    name: 'Momentum',
    description: 'Momentum',
    category: CategoryEnum.tech,
    categoryName: CategoryTextEnum.tech,
  },
  {
    id: 'Money Flow Index',
    name: 'Money Flow Index',
    description: 'Money Flow Index',
    category: CategoryEnum.tech,
    categoryName: CategoryTextEnum.tech,
  },
  {
    id: 'Moving Average',
    name: 'Moving Average',
    description: 'Moving Average',
    category: CategoryEnum.tech,
    categoryName: CategoryTextEnum.tech,
  },
  {
    id: 'Moving Average Adaptive',
    name: 'Moving Average Adaptive',
    description: 'Moving Average Adaptive',
    category: CategoryEnum.tech,
    categoryName: CategoryTextEnum.tech,
  },
  {
    id: 'Moving Average Channel',
    name: 'Moving Average Channel',
    description: 'Moving Average Channel',
    category: CategoryEnum.tech,
    categoryName: CategoryTextEnum.tech,
  },
  {
    id: 'Moving Average Double',
    name: 'Moving Average Double',
    description: 'Moving Average Double',
    category: CategoryEnum.tech,
    categoryName: CategoryTextEnum.tech,
  },
  {
    id: 'Moving Average Exponential',
    name: 'Moving Average Exponential',
    description: 'Moving Average Exponential',
    category: CategoryEnum.tech,
    categoryName: CategoryTextEnum.tech,
  },
  {
    id: 'Moving Average Hamming',
    name: 'Moving Average Hamming',
    description: 'Moving Average Hamming',
    category: CategoryEnum.tech,
    categoryName: CategoryTextEnum.tech,
  },
  {
    id: 'Moving Average Multiple',
    name: 'Moving Average Multiple',
    description: 'Moving Average Multiple',
    category: CategoryEnum.tech,
    categoryName: CategoryTextEnum.tech,
  },
  {
    id: 'Moving Average Triple',
    name: 'Moving Average Triple',
    description: 'Moving Average Triple',
    category: CategoryEnum.tech,
    categoryName: CategoryTextEnum.tech,
  },
  {
    id: 'Moving Average Weighted',
    name: 'Moving Average Weighted',
    description: 'Moving Average Weighted',
    category: CategoryEnum.tech,
    categoryName: CategoryTextEnum.tech,
  },
  {
    id: 'Net Volume',
    name: 'Net Volume',
    description: 'Net Volume',
    category: CategoryEnum.tech,
    categoryName: CategoryTextEnum.tech,
  },
  {
    id: 'On Balance Volume',
    name: 'On Balance Volume',
    description: 'On Balance Volume',
    category: CategoryEnum.tech,
    categoryName: CategoryTextEnum.tech,
  },
  {
    id: 'Parabolic SAR',
    name: 'Parabolic SAR',
    description: 'Parabolic SAR',
    category: CategoryEnum.tech,
    categoryName: CategoryTextEnum.tech,
  },
  {
    id: 'Pivot Points Standard',
    name: 'Pivot Points Standard',
    description: 'Pivot Points Standard',
    category: CategoryEnum.tech,
    categoryName: CategoryTextEnum.tech,
  },
  {
    id: 'Price Channel',
    name: 'Price Channel',
    description: 'Price Channel',
    category: CategoryEnum.tech,
    categoryName: CategoryTextEnum.tech,
  },
  {
    id: 'Price Oscillator',
    name: 'Price Oscillator',
    description: 'Price Oscillator',
    category: CategoryEnum.tech,
    categoryName: CategoryTextEnum.tech,
  },
  {
    id: 'Price Volume Trend',
    name: 'Price Volume Trend',
    description: 'Price Volume Trend',
    category: CategoryEnum.tech,
    categoryName: CategoryTextEnum.tech,
  },
  {
    id: 'Rank Correlation Index',
    name: 'Rank Correlation Index',
    description: 'Rank Correlation Index',
    category: CategoryEnum.tech,
    categoryName: CategoryTextEnum.tech,
  },
  {
    id: 'Rate Of Change',
    name: 'Rate Of Change',
    description: 'Rate Of Change',
    category: CategoryEnum.tech,
    categoryName: CategoryTextEnum.tech,
  },
  {
    id: 'Ratio',
    name: 'Ratio',
    description: 'Ratio',
    category: CategoryEnum.tech,
    categoryName: CategoryTextEnum.tech,
  },
  {
    id: 'Relative Strength Index',
    name: 'Relative Strength Index',
    description: 'Relative Strength Index',
    category: CategoryEnum.tech,
    categoryName: CategoryTextEnum.tech,
  },
  {
    id: 'Relative Vigor Index',
    name: 'Relative Vigor Index',
    description: 'Relative Vigor Index',
    category: CategoryEnum.tech,
    categoryName: CategoryTextEnum.tech,
  },
  {
    id: 'Relative Volatility Index',
    name: 'Relative Volatility Index',
    description: 'Relative Volatility Index',
    category: CategoryEnum.tech,
    categoryName: CategoryTextEnum.tech,
  },
  {
    id: 'SMI Ergodic Indicator/Oscillator',
    name: 'SMI Ergodic Indicator/Oscillator',
    description: 'SMI Ergodic Indicator/Oscillator',
    category: CategoryEnum.tech,
    categoryName: CategoryTextEnum.tech,
  },
  {
    id: 'Smoothed Moving Average',
    name: 'Smoothed Moving Average',
    description: 'Smoothed Moving Average',
    category: CategoryEnum.tech,
    categoryName: CategoryTextEnum.tech,
  },
  {
    id: 'Spread',
    name: 'Spread',
    description: 'Spread',
    category: CategoryEnum.tech,
    categoryName: CategoryTextEnum.tech,
  },
  {
    id: 'Standard Deviation',
    name: 'Standard Deviation',
    description: 'Standard Deviation',
    category: CategoryEnum.tech,
    categoryName: CategoryTextEnum.tech,
  },
  {
    id: 'Standard Error',
    name: 'Standard Error',
    description: 'Standard Error',
    category: CategoryEnum.tech,
    categoryName: CategoryTextEnum.tech,
  },
  {
    id: 'Standard Error Bands',
    name: 'Standard Error Bands',
    description: 'Standard Error Bands',
    category: CategoryEnum.tech,
    categoryName: CategoryTextEnum.tech,
  },
  {
    id: 'Stochastic',
    name: 'Stochastic',
    description: 'Stochastic',
    category: CategoryEnum.tech,
    categoryName: CategoryTextEnum.tech,
  },
  {
    id: 'Stochastic RSI',
    name: 'Stochastic RSI',
    description: 'Stochastic RSI',
    category: CategoryEnum.tech,
    categoryName: CategoryTextEnum.tech,
  },
  {
    id: 'SuperTrend',
    name: 'SuperTrend',
    description: 'SuperTrend',
    category: CategoryEnum.tech,
    categoryName: CategoryTextEnum.tech,
  },
  {
    id: 'Trend Strength Index',
    name: 'Trend Strength Index',
    description: 'Trend Strength Index',
    category: CategoryEnum.tech,
    categoryName: CategoryTextEnum.tech,
  },
  {
    id: 'Triple EMA',
    name: 'Triple EMA',
    description: 'Triple EMA',
    category: CategoryEnum.tech,
    categoryName: CategoryTextEnum.tech,
  },
  {
    id: 'TRIX',
    name: 'TRIX',
    description: 'TRIX',
    category: CategoryEnum.tech,
    categoryName: CategoryTextEnum.tech,
  },
  {
    id: 'True Strength Index',
    name: 'True Strength Index',
    description: 'True Strength Index',
    category: CategoryEnum.tech,
    categoryName: CategoryTextEnum.tech,
  },
  {
    id: 'Typical Price',
    name: 'Typical Price',
    description: 'Typical Price',
    category: CategoryEnum.tech,
    categoryName: CategoryTextEnum.tech,
  },
  {
    id: 'Ultimate Oscillator',
    name: 'Ultimate Oscillator',
    description: 'Ultimate Oscillator',
    category: CategoryEnum.tech,
    categoryName: CategoryTextEnum.tech,
  },
  {
    id: 'Volatility Close-to-Close',
    name: 'Volatility Close-to-Close',
    description: 'Volatility Close-to-Close',
    category: CategoryEnum.tech,
    categoryName: CategoryTextEnum.tech,
  },
  {
    id: 'Volatility Index',
    name: 'Volatility Index',
    description: 'Volatility Index',
    category: CategoryEnum.tech,
    categoryName: CategoryTextEnum.tech,
  },
  {
    id: 'Volatility O-H-L-C',
    name: 'Volatility O-H-L-C',
    description: 'Volatility O-H-L-C',
    category: CategoryEnum.tech,
    categoryName: CategoryTextEnum.tech,
  },
  {
    id: 'Volatility Zero Trend Close-to-Close',
    name: 'Volatility Zero Trend Close-to-Close',
    description: 'Volatility Zero Trend Close-to-Close',
    category: CategoryEnum.tech,
    categoryName: CategoryTextEnum.tech,
  },
  {
    id: 'Volume',
    name: 'Volume',
    description: 'Volume',
    category: CategoryEnum.tech,
    categoryName: CategoryTextEnum.tech,
  },
  {
    id: 'Volume Oscillator',
    name: 'Volume Oscillator',
    description: 'Volume Oscillator',
    category: CategoryEnum.tech,
    categoryName: CategoryTextEnum.tech,
  },
  {
    id: 'Volume Profile Fixed Range',
    name: 'Volume Profile Fixed Range',
    description: 'Volume Profile Fixed Range',
    category: CategoryEnum.tech,
    categoryName: CategoryTextEnum.tech,
  },
  {
    id: 'Volume Profile Visible Range',
    name: 'Volume Profile Visible Range',
    description: 'Volume Profile Visible Range',
    category: CategoryEnum.tech,
    categoryName: CategoryTextEnum.tech,
  },
  {
    id: 'Vortex Indicator',
    name: 'Vortex Indicator',
    description: 'Vortex Indicator',
    category: CategoryEnum.tech,
    categoryName: CategoryTextEnum.tech,
  },
  {
    id: 'VWAP',
    name: 'VWAP',
    description: 'VWAP',
    category: CategoryEnum.tech,
    categoryName: CategoryTextEnum.tech,
  },
  {
    id: 'VWMA',
    name: 'VWMA',
    description: 'VWMA',
    category: CategoryEnum.tech,
    categoryName: CategoryTextEnum.tech,
  },
  {
    id: 'Williams %R',
    name: 'Williams %R',
    description: 'Williams %R',
    category: CategoryEnum.tech,
    categoryName: CategoryTextEnum.tech,
  },
  {
    id: 'Williams Alligator',
    name: 'Williams Alligator',
    description: 'Williams Alligator',
    category: CategoryEnum.tech,
    categoryName: CategoryTextEnum.tech,
  },
  {
    id: 'Williams Fractal',
    name: 'Williams Fractal',
    description: 'Williams Fractal',
    category: CategoryEnum.tech,
    categoryName: CategoryTextEnum.tech,
  },
  {
    id: 'Zig Zag',
    name: 'Zig Zag',
    description: 'Zig Zag',
    category: CategoryEnum.tech,
    categoryName: CategoryTextEnum.tech,
  },
//链上
  {
    id: 'BTC_MVRV',
    name: 'BTC MVRV',
    description: 'BTC Market value to Realized value',
    category: CategoryEnum.chain,
    categoryName: CategoryTextEnum.chain,
    code: 'BTC_MVRV',
  },
  {
    id: 'BTC_LTH_STH_POSITION',
    name: 'BTC LTH/STH Position',
    description: 'BTC长短期持币者的持币数量',
    category: CategoryEnum.chain,
    categoryName: CategoryTextEnum.chain,
    code: 'BTC_LTH_STH_POSITION',
  },
  {
    id: 'BTC_LTH_NET_POSITION_CHANGE_30D',
    name: 'BTC LTH NET Position Change',
    description: 'BTC长期持币者持币数量变化',
    category: CategoryEnum.chain,
    categoryName: CategoryTextEnum.chain,
    code: 'BTC_LTH_NET_POSITION_CHANGE_30D',
  },
  {
    id: 'BTC_PERCENT_OF_SUPPLY_LAST_ACTIVE_1Y',
    name: 'BTC Percent of Supply Last Active 1+ Years Ago',
    description: '持币时间一年以上持币者持币量占全部BTC比例',
    category: CategoryEnum.chain,
    categoryName: CategoryTextEnum.chain,
    code: 'BTC_PERCENT_OF_SUPPLY_LAST_ACTIVE_1Y',
  },
  {
    id: 'BTC_NET_REALIZED_PROFIT_LOSS',
    name: 'BTC: Net Realized Profit/Loss',
    description: 'BTC已实现盈亏',
    category: CategoryEnum.chain,
    categoryName: CategoryTextEnum.chain,
    code: 'BTC_NET_REALIZED_PROFIT_LOSS',
  },
  {
    id: 'BTC_LONG_TERM_HOLDER_NET_REALIZED_PROFIT_LOSS',
    name: 'BTC Long-Term Holder Net Realized Profit / Loss',
    description: 'BTC LTH已实现盈亏',
    category: CategoryEnum.chain,
    categoryName: CategoryTextEnum.chain,
    code: 'BTC_LONG_TERM_HOLDER_NET_REALIZED_PROFIT_LOSS',
  },
  {
    id: 'BTC_SHORT_TERM_HOLDER_NET_REALIZED_PROFIT_LOSS',
    name: 'BTC Short-Term Holder Net Realized Profit / Loss',
    description: 'BTC STH已实现盈亏',
    category: CategoryEnum.chain,
    categoryName: CategoryTextEnum.chain,
    code: 'BTC_SHORT_TERM_HOLDER_NET_REALIZED_PROFIT_LOSS',
  },
  {
    id: 'BTC_NET_UNREALIZED_PROFIT_LOSS_NUPL',
    name: 'BTC Net Unrealized Profit/Loss (NUPL)',
    description: 'BTC未实现盈亏',
    category: CategoryEnum.chain,
    categoryName: CategoryTextEnum.chain,
    code: 'BTC_NET_UNREALIZED_PROFIT_LOSS_NUPL',
  },
  {
    id: 'BTC_LONG_TERM_HOLDER_NUPL',
    name: 'BTC Long Term Holder NUPL',
    description: 'BTC LTH 未实现盈亏',
    category: CategoryEnum.chain,
    categoryName: CategoryTextEnum.chain,
    code: 'BTC_LONG_TERM_HOLDER_NUPL',
  },
  {
    id: 'BTC_SHORT_TERM_HOLDER_NUPL',
    name: 'BTC Short Term Holder NUPL',
    description: 'BTC STH 未实现盈亏',
    category: CategoryEnum.chain,
    categoryName: CategoryTextEnum.chain,
    code: 'BTC_SHORT_TERM_HOLDER_NUPL',
  },
  {
    id: 'BTC_SHORT_TERM_HOLDER_COST_BASIS_MODEL',
    name: 'BTC Short-Term Holder Cost Basis Model',
    description: '短期持币者成本',
    category: CategoryEnum.chain,
    categoryName: CategoryTextEnum.chain,
    code: 'BTC_SHORT_TERM_HOLDER_COST_BASIS_MODEL',
  },
  {
    id: 'BTC Realized Profit/Loss Ratio (90D MA)',
    name: 'BTC Realized Profit/Loss Ratio (90D MA)',
    description: '已实现盈亏比（90天移动平均）',
    category: CategoryEnum.chain,
    categoryName: CategoryTextEnum.chain,
    code: 'BTC_REALIZED_PROFIT_LOSS_RATIO_90D_MA',
  },
  {
    id: 'BTC MVRV Extreme Deviation Pricing Bands (365d)',
    name: 'BTC MVRV Extreme Deviation Pricing Bands (365d)',
    description: 'BTC MVRV极值价格带（1Y）',
    category: CategoryEnum.chain,
    categoryName: CategoryTextEnum.chain,
    code: 'BTC_MVRV_EXTREME_DEVIATION_PRICING_BANDS_365D',
  },

// 流动性-liquidity
  {
    id: 'BTC NET FLOW',
    name: 'US BTC SPOT ETF NETFLOW',
    description: '美国BTC现货ETF单日净流入/流出',
    category: CategoryEnum.liquidity,
    categoryName: CategoryTextEnum.liquidity,
    code: 'BTC_ETF_FLOW',
  },
  {
    id: 'Stablecoin Supply',
    name: 'Stablecoin Supply',
    description: 'USDT和USDC的供应量',
    category: CategoryEnum.liquidity,
    categoryName: CategoryTextEnum.liquidity,
    code: 'STABLECOIN_SUPPLY',
  },
  {
    id: 'Stablecoin Supply Change',
    name: 'Stablecoin Supply Change',
    description: 'USDT和USDC的供应变动量',
    category: CategoryEnum.liquidity,
    categoryName: CategoryTextEnum.liquidity,
    code: 'STABLECOIN_SUPPLY_CHANGE',
  },
  {
    id: 'CEX BTC NETFLOW',
    name: 'CEX BTC NETFLOW',
    description: 'BTC流入流出中心化交易所',
    category: CategoryEnum.liquidity,
    categoryName: CategoryTextEnum.liquidity,
    code: 'CEX_BTC_FLOW',
  },
  {
    id: 'CEX_ORDERBOOK_DIFF',
    name: 'CEX BTC Orderbook Diff',
    description: 'BTC在各家CEX里的不同depth下的orderbook diff',
    category: CategoryEnum.liquidity,
    categoryName: CategoryTextEnum.liquidity,
    code: 'CEX_ORDERBOOK_DIFF',
  },
  {
    id: 'CEX_SPOT_VOLUME',
    name: 'CEX现货交易量',
    description: '各家CEX交易所内的现货交易量',
    category: CategoryEnum.liquidity,
    categoryName: CategoryTextEnum.liquidity,
    code: 'CEX_SPOT_VOLUME',
  },
  {
    id: 'CEX_FUTURES_VOLUME',
    name: 'CEX合约交易量',
    description: '各家CEX交易所内的合约交易量',
    category: CategoryEnum.liquidity,
    categoryName: CategoryTextEnum.liquidity,
    code: 'CEX_FUTURES_VOLUME',
  },
  {
    id: 'CEX_LIQUIDATIONS',
    name: 'CEX中BTC合约爆仓数据',
    description: '各家CEX交易所内的合约多空爆仓量',
    category: CategoryEnum.liquidity,
    categoryName: CategoryTextEnum.liquidity,
    code: 'CEX_LIQUIDATIONS',
  },
  // 情绪
  {
    id: 'BINANCE_USDT_LENDING_RATE',
    name: 'Binance USDT活期借贷利率（年化）',
    description: 'Binance USDT活期借贷利率（年化）',
    category: CategoryEnum.sentiment,
    categoryName: CategoryTextEnum.sentiment,
    code: 'BINANCE_USDT_LENDING_RATE',
  },
  {
    id: 'BTC FUNDING RATE',
    name: 'BTC持仓加权资金费率（年化）',
    description: 'BTC持仓加权后的资金费率（年化）',
    category: CategoryEnum.sentiment,
    categoryName: CategoryTextEnum.sentiment,
    code: 'BTC_FUNDING_RATE',
  },
  {
    id: 'BTC_EXCHANGE_PREMIUM',
    name: 'BTC Coinbase over Binance Premium/Discount',
    description: 'BTC现货价格在Coinbase和Binance的溢价/折价百分比',
    category: CategoryEnum.sentiment,
    categoryName: CategoryTextEnum.sentiment,
    code: 'BTC_EXCHANGE_PREMIUM',
  },
  {
    id: 'CMC_FEAR_AND_GREED_INDEX',
    name: 'CMC Crypto Fear and Greed Index',
    description: 'CMC恐慌&贪婪指数',
    category: CategoryEnum.sentiment,
    categoryName: CategoryTextEnum.sentiment,
    code: 'CMC_FEAR_AND_GREED_INDEX',
  },
  {
    id: 'CMC_ALTCOIN_SEASON_INDEX',
    name: 'CMC Altcoin Season Index',
    description: 'CMC山寨季指数',
    category: CategoryEnum.sentiment,
    categoryName: CategoryTextEnum.sentiment,
    code: 'CMC_ALTCOIN_SEASON_INDEX',
  },
  {
    id: 'REGIONAL_MOM_PRICE_CHANGE',
    name: 'Regional Month-over-Month Price Change',
    description: '美/亚/欧情绪',
    category: CategoryEnum.sentiment,
    categoryName: CategoryTextEnum.sentiment,
    code: 'REGIONAL_MOM_PRICE_CHANGE',
  },
  {
    id: 'FUTURES_ANNUALIZED_ROLLING_BASIS_3M',
    name: 'Futures Annualized Rolling Basis (3M)',
    description: '3个月期货与现货溢价（基差交易年化）',
    category: CategoryEnum.sentiment,
    categoryName: CategoryTextEnum.sentiment,
    code: 'FUTURES_ANNUALIZED_ROLLING_BASIS_3M',
  },
  //期权
  {
    id: 'BTC_OPTIONS_25_DELTA_SKEW',
    name: 'BTC Options 25 delta skew',
    description: 'Deribit上BTC Options 1week/1month/3month/6month 25  Delta Skew',
    category: CategoryEnum.options,
    categoryName: CategoryTextEnum.options,
    code: 'BTC_OPTIONS_SKEW',
  },
  {
    id: 'BTC_OPTIONS_IV',
    name: 'BTC Options ATM Implied Volatility',
    description: 'Deribit上BTC 1week/1month/3month/6month IV',
    category: CategoryEnum.options,
    categoryName: CategoryTextEnum.options,
    code: 'BTC_OPTIONS_IV',
  },
  {
    id: 'BTC_OPTIONS_ATM_IV_PERCENTILE',
    name: 'BTC Options ATM Implied Volatility Percentile',
    description: 'Deribit上各个期限期权的BTC ATM IV在相应时间窗口下的percentile',
    category: CategoryEnum.options,
    categoryName: CategoryTextEnum.options,
    code: 'BTC_OPTIONS_ATM_IV_PERCENTILE',
  },
  {
    id: 'BTC Implied Volatility Index (DVOL)',
    name: 'BTC Implied Volatility Index (DVOL)',
    description: 'Deribit DVOL',
    category: CategoryEnum.options,
    categoryName: CategoryTextEnum.options,
    code: 'BTC_IMPLIED_VOLATILITY_INDEX_DVOL',
  },
  // 市场微观结构
  {
    id: 'BTC_HOLDER_DISTRIBUTION',
    name: 'BTC筹码持仓图',
    description: '链上不同持币量的持币者的持币量变动',
    category: CategoryEnum.market,
    categoryName: CategoryTextEnum.market,
    code: 'BTC_HOLDER_DISTRIBUTION',
  },
  {
    id: 'MARKET_DOMINANCE',
    name: 'Market dominance',
    description: 'Crypto市场各类标的市占率',
    category: CategoryEnum.market,
    categoryName: CategoryTextEnum.market,
    code: 'MARKET_DOMINANCE',
  },
]
export const indicatorMapFull = Object.fromEntries(indicatorList.map(item => [item.id, item]));